//POO = PROGRAMAÇÃO ORINETADA A OBJETOS

//FUNÇÕES SIGUINIFICATIVAS(ESCOPO OU EMCAPSULAMENTO)= organizado em um mesmo contexto

//CRIAR UMA NOVA INSTANCIA = CRIA UM CLONE DO OBJETO PARA UTILIZAR OS ATRIBUTOS DA CLASSE CRIADA ANTES

//CLASSE(OBJETO) = FORMA DE ORGANIZAR O CODIGO QUE TENHA VARIAVEIS E FUNÇÕES DENTRO DE UM MODELO
//ELA CONTEM UM CONJUNTO DE FUNÇÕES E UM CONJUNTO DE VARIAVEIS.

//QUANDO VC CRIA UMA CLASSE VOCÊ CRIA: CLASSE => PROPRIEDADES(VARIAVEIS)=> METODOS(AÇÕES = FUNÇÕES)

//MODELO = E UM EXEPLO DE CODIGO PRE DESCRITO PARA QUANDO SE FOR CRIAR UMA INSTÂNCIA

//VARIAVEL = ATRIBUTOS
//FUNÇÕES = METODOS